mysql:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: test
  restart: always
gplcart:
  image: gplcart/core
  ports:
    - 8080:80
  links:
    - mysql
  restart: always