gplcart:
  build: .
  links:
    - db
  ports:
    - 8080:80
db:
  container_name: mariadb
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: test
  ports:
    - 3306:3306
phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin:4.7
  links:
    - db
  ports:
    - 8181:80