mysql:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: test
server:
  image: gplcart/core
  links:
    - mysql
  ports:
    - 8080:80
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  ports:
    - 8181:80
